export { default as ComingSoon } from './ComingSoon'
export { default as Home } from './Home'
export { default as SupportNest } from './SupportNest'
export { default as NotFound } from './404Page'
export { default as Features } from './Features'
export { default as FullscreenMoodLandscape } from './AR'
export { default as Panorama } from './Panorama'
