export { default as userRoutes } from './user.js'
export { default as chatRoutes } from './chats.js'
export { default as botRoutes } from './bot.js'
export { default as moodRoutes } from './mood.js'
export { default as excerciseRoutes } from './excercise.js'
